/*******************************************************************************
* AsyncTask generated by MVN.RLLib using UE Explorer.
* MVN.RLLib © 2019 Martin VN. All rights reserved.
* All rights belong to their respective owners.
*******************************************************************************/
class AsyncTask extends Object
    implements(IDisposable);

var privatewrite bool bComplete;
var privatewrite bool bDisposed;
var privatewrite Error Error;