/*******************************************************************************
* StringObjectMap generated by MVN.RLLib using UE Explorer.
* MVN.RLLib © 2019 Martin VN. All rights reserved.
* All rights belong to their respective owners.
*******************************************************************************/
class StringObjectMap extends Component;

var private const Map_Mirror Map;