/*******************************************************************************
* RuntimeParameterBase_X generated by MVN.RLLib using UE Explorer.
* MVN.RLLib ? 2019 Martin VN. All rights reserved.
* All rights belong to their respective owners.
*******************************************************************************/
class RuntimeParameterBase_X extends Object
    abstract
    editinlinenew
    collapsecategories
    hidecategories(Object);

var() private name ParameterName;
