/*******************************************************************************
* AkDialogueEvent generated by MVN.RLLib using UE Explorer.
* MVN.RLLib © 2019 Martin VN. All rights reserved.
* All rights belong to their respective owners.
*******************************************************************************/
class AkDialogueEvent extends Object
    collapsecategories
    hidecategories(Object);

var() private const array<private AkSwitch> Arguments;