/*******************************************************************************
* AkSoundCue generated by MVN.RLLib using UE Explorer.
* MVN.RLLib ? 2019 Martin VN. All rights reserved.
* All rights belong to their respective owners.
*******************************************************************************/
class AkSoundCue extends Object;

var() private AkBank RequiredBank;
var() private string StartEvent;
var() private string StopEvent;