/*******************************************************************************
* DataAsset_ESportsTeam_TA generated by MVN.RLLib using UE Explorer.
* MVN.RLLib © 2019 Martin VN. All rights reserved.
* All rights belong to their respective owners.
*******************************************************************************/
class DataAsset_ESportsTeam_TA extends Object
    hidecategories(Object);

var() private int TeamID;
var() private editinline ProductAssetReference_TA ESportsTeamReference;