/*******************************************************************************
* SpecialPickup_BallLasso_TA generated by MVN.RLLib using UE Explorer.
* MVN.RLLib ? 2019 Martin VN. All rights reserved.
* All rights belong to their respective owners.
*******************************************************************************/
class SpecialPickup_BallLasso_TA extends SpecialPickup_Spring_TA
    notplaceable
    hidecategories(Navigation);

var() private name SpringMeshSlackParam;