/*******************************************************************************
* MaterialExpressionEffectsIntensity generated by MVN.RLLib using UE Explorer.
* MVN.RLLib ? 2019 Martin VN. All rights reserved.
* All rights belong to their respective owners.
*******************************************************************************/
class MaterialExpressionEffectsIntensity extends MaterialExpression
    hidecategories(Object);

defaultproperties
{
    MenuCategories(0)=Accessibility
}