/*******************************************************************************
* StaticCameraActor generated by MVN.RLLib using UE Explorer.
* MVN.RLLib ? 2019 Martin VN. All rights reserved.
* All rights belong to their respective owners.
*******************************************************************************/
class StaticCameraActor extends CameraActor
    placeable
    hidecategories(Navigation);

defaultproperties
{
    bStatic=true
}